site_name: MEV REST API
site_description: Documentation for the MEV RESTful API

repo_url: https://github.com/qbrc-cnap/mev-backend

markdown_extensions:
 - toc:
    anchorlink: True
 - admonition
 - codehilite
 - mkautodoc

theme: readthedocs
extra_css: [style.css]

nav:
 - Home: 'index.md'
 - Install: 'install.md'
 - API: 
   - Intro: 'api.md'
   - Data Structures:
      - Attributes: 'attributes.md'
      - Observations and Features: 'elements.md'
      - Workspaces: 'workspaces.md'
      - Resources: 'resources.md'
   - Authentication: 'auth.md'
