version: '3.7'

services:

  api:
    build:
      context: ./mev
    command: gunicorn mev.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/www/static
    expose:
      - 8000
    env_file:
      - ./env_vars.txt
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    depends_on:
      - db
      - redis
  
  db:
    build:
      context: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_vars.txt


  redis:
    image: redis:6.0.5-alpine


  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/www/static
    ports:
      - 8081:80
    depends_on:
      - api


volumes:
  postgres_data:
  static_volume:
      